### ISSUE TITLE
Hubspot's greater than and less than operators interchanged

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-hubspot#41]
## Repro Steps:
1. Run the scenario below
```yml 
scenario: Contact API with operators
description: This scenario proves that the smooth operators are working when validating fields of a Contact

steps:
- step: When I create or update a hubspot contact
  data:
    contact:
        email: hspttesting@thisisjust.atomatest.com
        firstName: jake
        lastName: lozan
        company: HS Corp
        date_of_birth: 1992-05-151T00:00:00
- step: Then the email field on hubspot contact hspttesting@thisisjust.atomatest.com should not be hspttesting@thisisjust.atomatest.com
- step: And the firstname field on Hubspot contact hspttesting@thisisjust.atomatest.com should contain J
- step: And the lastname field on Hubspot contact hspttesting@thisisjust.atomatest.com should not contain be
- step: And the company field on Hubspot contact hspttesting@thisisjust.atomatest.com should be HS Corp
- step: And the date_of_birth field on Hubspot contact hspttesting@thisisjust.atomatest.com should be less than 1994-05-151T00:00:00
- step: And the createdate field on Hubspot contact hspttesting@thisisjust.atomatest.com should be greater than 2000-04-121T00:00:00
- step: Finally, delete the hspttesting@thisisjust.atomatest.com hubspot contact

```

## Actual Result:
![image](https://user-images.githubusercontent.com/54615569/75020383-9e5ac880-54cd-11ea-9dc7-1b487adfe9e2.png)
