### ISSUE TITLE
New Step: Enroll a HubSpot Contact into a Workflow

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-hubspot#7]
### As a Crank user, I should be able to enroll a HubSpot Contact into a Workflow

**Proposed Step Name**: `Enroll a HubSpot Contact into a Workflow`
**Proposed Step Expression**: `enroll the (?<email>.+) hubspot contact into workflow (?<workflow>.+)`

**Proposed Step Fields**:
- `email` (type `EMAIL`), the email address of the Hubspot Contact
- `workflow` (type `ANYSCALAR`), either the name of the workflow, or the numeric ID of the workflow.

**Notes**
- [x] If the `workflow` provided is numeric, it should just use the numeric value when making the call to HubSpot.
- [x] If the `workflow` provided is non-numeric, it should first query HubSpot for a workflow with the given name.
  - [x] If more than one workflow is returned, and error should be returned `Can't enroll %s into %s: found more than one workflow with that name.`
- [x] If the workflow enroll API call returns a `404`, the step should return an error (indicating that the Contact or Workflow does not exist)
- [x] If the workflow enroll API call returns a `412`, the step should return a fail, including the specific preconditions that were not met (should be included in the response body error, see API docs linked below for details)

**Reference**
- https://github.com/MadKudu/node-hubspot/blob/master/lib/workflow.js (note: that this is not documented, but as the code shows, it's clearly implemented)
- https://developers.hubspot.com/docs/methods/workflows/add_contact

-----

### Example Scenario

```yml
scenario: Enroll in Workflow UAT
description: Proves that the Enroll a HubSpot Contact into a Workflow step is working

tokens:
  test
    email: atommy@example.com

steps:
- step: Given I create a HubSpot Contact
  data:
    contact:
      email: '{{test.email}}'
      lifecyclestage: lead
- step: When I enroll the {{test.email}} Contact into workflow MQL and Email
- step: Then the lifecyclestage field on HubSpot Contact {{test.email}} should be marketingqualifiedlead
  failAfter: 60
- step: Finally, delete the {{test.email}} HubSpot Contact
```
