### ISSUE TITLE
New Step Check Workflow Enrollment of a HubSpot Contact

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-hubspot#8]
### As a Crank user, I should be able to check that a HubSpot Contact is enrolled in a Workflow

**Proposed Step Name**: `Check Workflow Enrollment of a HubSpot Contact`
**Proposed Step Expression**: `the (?<email>.+) hubspot contact should be enrolled in workflow (?<workflow>.+)`

**Proposed Step Fields**:
- `email` (type `EMAIL`), the email address of the Hubspot Contact
- `workflow` (type `ANYSCALAR`), either the name of the workflow, or the numeric ID of the workflow.

**Notes**
- [x] If the `workflow` provided is numeric, it should be compared with the Workflow ID in the response object.
- [x] If the `workflow` provided is non-numeric, it should be compared with the Workflow Name in the response object.
  - [x] It's possible that a contact is enrolled in more than one Workflow, which is okay.  The step should pass if any one of the returned workflows matches the given data.
- [x] If the step result is a failure (e.g. Contact is not enrolled in given workflow), the names of all workflows the contact _is_ enrolled in (if any) should be displayed in the failure message.

**Reference**
- https://github.com/MadKudu/node-hubspot/blob/master/lib/workflow.js#L34
- https://developers.hubspot.com/docs/methods/workflows/current_enrollments

-----

### Example Scenario

```yml
scenario: Check Workflow Enrollment UAT
description: Proves that the Check Workflow Enrollment of a HubSpot Contact step is working

tokens:
  test
    email: atommy@example.com

steps:
- step: Given I create a HubSpot Contact
  data:
    contact:
      email: '{{test.email}}'
- step: When I enroll the {{test.email}} Contact into workflow MQL and Email
- step: Then the {{test.email}} hubspot contact should be enrolled in workflow MQL and Email
- step: Finally, delete the {{test.email}} HubSpot Contact
```
